"""
theme_engine.py
Centralized theme system for MediaBrain.

Provides three built-in themes (light, dark, high-contrast) and
generates QSS stylesheets from color palettes. New themes can be
added by defining a palette dict.

Usage:
    from theme_engine import ThemeEngine
    engine = ThemeEngine()
    qss = engine.get_stylesheet("dark")
    app.setStyleSheet(qss)
"""

import logging

logger = logging.getLogger(__name__)


# ============================================================
# Color Palettes
# ============================================================

PALETTE_LIGHT = {
    "name": "Light",
    # Base
    "bg_primary": "#f8f9fa",
    "bg_secondary": "#ffffff",
    "bg_tertiary": "#e9ecef",
    "bg_sidebar": "#e2e6ea",
    "bg_input": "#ffffff",
    "bg_hover": "#dee2e6",
    "bg_selected": "#4a90d9",
    "bg_alt_row": "#f0f2f5",
    # Text
    "text_primary": "#212529",
    "text_secondary": "#495057",
    "text_muted": "#868e96",
    "text_on_accent": "#ffffff",
    # Accent
    "accent": "#4a90d9",
    "accent_hover": "#3a7bc8",
    "accent_light": "#e8f0fe",
    # Borders
    "border": "#ced4da",
    "border_light": "#dee2e6",
    "border_focus": "#4a90d9",
    # Semantic
    "danger": "#dc3545",
    "success": "#28a745",
    "warning": "#ffc107",
    "favorite": "#f0ad4e",
    # Sizing
    "font_size": "13px",
    "font_size_small": "11px",
    "font_size_h1": "18px",
    "font_size_h2": "15px",
    "border_radius": "5px",
    "spacing": "8px",
    "padding": "6px 12px",
}

PALETTE_DARK = {
    "name": "Dark",
    # Base
    "bg_primary": "#1e1e2e",
    "bg_secondary": "#282840",
    "bg_tertiary": "#313152",
    "bg_sidebar": "#181828",
    "bg_input": "#2a2a42",
    "bg_hover": "#3a3a5c",
    "bg_selected": "#5b8dd9",
    "bg_alt_row": "#242438",
    # Text
    "text_primary": "#e0e0e8",
    "text_secondary": "#b0b0c0",
    "text_muted": "#707088",
    "text_on_accent": "#ffffff",
    # Accent
    "accent": "#5b8dd9",
    "accent_hover": "#7aa3e5",
    "accent_light": "#2a3a5c",
    # Borders
    "border": "#404060",
    "border_light": "#353550",
    "border_focus": "#5b8dd9",
    # Semantic
    "danger": "#e55b68",
    "success": "#4caf80",
    "warning": "#e8b84a",
    "favorite": "#e8b84a",
    # Sizing
    "font_size": "13px",
    "font_size_small": "11px",
    "font_size_h1": "18px",
    "font_size_h2": "15px",
    "border_radius": "5px",
    "spacing": "8px",
    "padding": "6px 12px",
}

PALETTE_HIGH_CONTRAST = {
    "name": "High Contrast",
    # Base
    "bg_primary": "#000000",
    "bg_secondary": "#1a1a1a",
    "bg_tertiary": "#2a2a2a",
    "bg_sidebar": "#0a0a0a",
    "bg_input": "#1a1a1a",
    "bg_hover": "#333333",
    "bg_selected": "#ffcc00",
    "bg_alt_row": "#111111",
    # Text
    "text_primary": "#ffffff",
    "text_secondary": "#e0e0e0",
    "text_muted": "#aaaaaa",
    "text_on_accent": "#000000",
    # Accent
    "accent": "#ffcc00",
    "accent_hover": "#ffdd44",
    "accent_light": "#332200",
    # Borders
    "border": "#ffffff",
    "border_light": "#888888",
    "border_focus": "#ffcc00",
    # Semantic
    "danger": "#ff4444",
    "success": "#44ff44",
    "warning": "#ffcc00",
    "favorite": "#ffcc00",
    # Sizing - larger for accessibility
    "font_size": "15px",
    "font_size_small": "13px",
    "font_size_h1": "22px",
    "font_size_h2": "18px",
    "border_radius": "3px",
    "spacing": "10px",
    "padding": "8px 14px",
}

# Registry of all available themes
THEMES = {
    "light": PALETTE_LIGHT,
    "dark": PALETTE_DARK,
    "high-contrast": PALETTE_HIGH_CONTRAST,
}


# ============================================================
# QSS Template
# ============================================================

QSS_TEMPLATE = """
/* MediaBrain Theme: {name} */
/* Generated by theme_engine.py */

/* === Global === */
QWidget {{
    background-color: {bg_primary};
    color: {text_primary};
    font-size: {font_size};
    font-family: "Segoe UI", "Helvetica Neue", sans-serif;
}}

/* === Main Window === */
QMainWindow {{
    background-color: {bg_primary};
}}

/* === Sidebar === */
QWidget#Sidebar {{
    background-color: {bg_sidebar};
    border-right: 1px solid {border};
}}

QWidget#Sidebar QPushButton {{
    background-color: transparent;
    border: none;
    border-radius: {border_radius};
    padding: {padding};
    text-align: left;
    font-size: {font_size};
    color: {text_primary};
    margin: 2px 6px;
}}

QWidget#Sidebar QPushButton:hover {{
    background-color: {bg_hover};
}}

QWidget#Sidebar QPushButton:pressed {{
    background-color: {accent_light};
}}

/* === Buttons === */
QPushButton {{
    background-color: {bg_tertiary};
    border: 1px solid {border};
    padding: {padding};
    border-radius: {border_radius};
    color: {text_primary};
    font-size: {font_size};
    min-height: 28px;
}}

QPushButton:hover {{
    background-color: {bg_hover};
    border-color: {border_focus};
}}

QPushButton:pressed {{
    background-color: {accent};
    color: {text_on_accent};
}}

QPushButton:disabled {{
    background-color: {bg_tertiary};
    color: {text_muted};
    border-color: {border_light};
}}

/* === Input fields === */
QLineEdit {{
    background-color: {bg_input};
    border: 1px solid {border};
    padding: 6px 10px;
    border-radius: {border_radius};
    color: {text_primary};
    font-size: {font_size};
    min-height: 28px;
}}

QLineEdit:focus {{
    border-color: {border_focus};
    border-width: 2px;
}}

QLineEdit::placeholder {{
    color: {text_muted};
}}

/* === ComboBox === */
QComboBox {{
    background-color: {bg_input};
    border: 1px solid {border};
    padding: 5px 10px;
    border-radius: {border_radius};
    color: {text_primary};
    font-size: {font_size};
    min-height: 28px;
}}

QComboBox:hover {{
    border-color: {border_focus};
}}

QComboBox::drop-down {{
    border: none;
    width: 24px;
}}

QComboBox QAbstractItemView {{
    background-color: {bg_secondary};
    border: 1px solid {border};
    color: {text_primary};
    selection-background-color: {bg_selected};
    selection-color: {text_on_accent};
}}

/* === CheckBox === */
QCheckBox {{
    spacing: 8px;
    font-size: {font_size};
    color: {text_primary};
}}

QCheckBox::indicator {{
    width: 18px;
    height: 18px;
    border: 2px solid {border};
    border-radius: 3px;
    background-color: {bg_input};
}}

QCheckBox::indicator:checked {{
    background-color: {accent};
    border-color: {accent};
}}

/* === Labels === */
QLabel {{
    background-color: transparent;
    color: {text_primary};
    font-size: {font_size};
}}

/* === ScrollArea === */
QScrollArea {{
    background-color: transparent;
    border: none;
}}

QScrollBar:vertical {{
    background-color: {bg_primary};
    width: 10px;
    margin: 0;
}}

QScrollBar::handle:vertical {{
    background-color: {border};
    border-radius: 4px;
    min-height: 30px;
    margin: 2px;
}}

QScrollBar::handle:vertical:hover {{
    background-color: {text_muted};
}}

QScrollBar::add-line:vertical,
QScrollBar::sub-line:vertical {{
    height: 0;
}}

QScrollBar:horizontal {{
    background-color: {bg_primary};
    height: 10px;
}}

QScrollBar::handle:horizontal {{
    background-color: {border};
    border-radius: 4px;
    min-width: 30px;
    margin: 2px;
}}

/* === ListView === */
QListView {{
    background-color: {bg_secondary};
    border: 1px solid {border_light};
    border-radius: {border_radius};
    outline: none;
    font-size: {font_size};
}}

QListView::item {{
    padding: 4px 8px;
    border-bottom: 1px solid {border_light};
    min-height: 44px;
}}

QListView::item:hover {{
    background-color: {bg_hover};
}}

QListView::item:selected {{
    background-color: {bg_selected};
    color: {text_on_accent};
}}

QListView::item:alternate {{
    background-color: {bg_alt_row};
}}

/* === ListWidget (used in StatsView) === */
QListWidget {{
    background-color: {bg_secondary};
    border: 1px solid {border_light};
    border-radius: {border_radius};
    font-size: {font_size};
}}

QListWidget::item {{
    padding: 3px 6px;
    min-height: 24px;
}}

/* === Frames === */
QFrame {{
    background-color: transparent;
}}

QFrame[frameShape="6"] {{
    background-color: {bg_secondary};
    border: 1px solid {border_light};
    border-radius: {border_radius};
}}

/* === Splitter === */
QSplitter::handle {{
    background-color: {border_light};
    width: 2px;
}}

QSplitter::handle:hover {{
    background-color: {accent};
}}

/* === Menu === */
QMenu {{
    background-color: {bg_secondary};
    border: 1px solid {border};
    padding: 4px 0;
    border-radius: {border_radius};
    font-size: {font_size};
}}

QMenu::item {{
    padding: 6px 28px 6px 20px;
    color: {text_primary};
}}

QMenu::item:selected {{
    background-color: {bg_selected};
    color: {text_on_accent};
}}

QMenu::separator {{
    height: 1px;
    background-color: {border_light};
    margin: 4px 8px;
}}

/* === GroupBox === */
QGroupBox {{
    border: 1px solid {border_light};
    border-radius: {border_radius};
    margin-top: 12px;
    padding-top: 16px;
    font-size: {font_size};
    color: {text_primary};
}}

QGroupBox::title {{
    subcontrol-origin: margin;
    subcontrol-position: top left;
    padding: 0 8px;
    color: {text_secondary};
    font-weight: bold;
}}

/* === TabWidget === */
QTabWidget::pane {{
    border: 1px solid {border};
    border-radius: {border_radius};
    background-color: {bg_secondary};
}}

QTabBar::tab {{
    background-color: {bg_tertiary};
    border: 1px solid {border};
    padding: 8px 16px;
    font-size: {font_size};
    color: {text_secondary};
}}

QTabBar::tab:selected {{
    background-color: {bg_secondary};
    color: {text_primary};
    border-bottom-color: {bg_secondary};
    font-weight: bold;
}}

QTabBar::tab:hover {{
    background-color: {bg_hover};
}}

/* === ToolTip === */
QToolTip {{
    background-color: {bg_secondary};
    color: {text_primary};
    border: 1px solid {border};
    padding: 4px 8px;
    font-size: {font_size_small};
}}

/* === Dialog === */
QDialog {{
    background-color: {bg_primary};
}}

QDialogButtonBox QPushButton {{
    min-width: 80px;
}}

/* === MessageBox === */
QMessageBox {{
    background-color: {bg_primary};
}}

/* === Named Label Styles === */
QLabel#mutedLabel {{
    color: {text_muted};
    font-size: {font_size_small};
}}

QLabel#dangerLabel {{
    color: {danger};
    font-weight: bold;
}}

QLabel#sectionHeader {{
    font-size: {font_size_h2};
    font-weight: bold;
    padding-top: 8px;
    padding-bottom: 4px;
}}

QLabel#pageTitle {{
    font-size: {font_size_h1};
    font-weight: bold;
    padding-bottom: 8px;
}}
"""


# ============================================================
# ThemeEngine
# ============================================================

class ThemeEngine:
    """Manages theme palettes and generates QSS stylesheets.

    Supports built-in themes (light, dark, high-contrast) and
    custom themes via register_theme().
    """

    def __init__(self):
        self._themes = dict(THEMES)

    def list_themes(self) -> list:
        """Returns list of (key, display_name) tuples."""
        return [(k, v["name"]) for k, v in self._themes.items()]

    def get_palette(self, theme_key: str) -> dict:
        """Returns the palette dict for a theme."""
        return self._themes.get(theme_key, PALETTE_LIGHT)

    def get_stylesheet(self, theme_key: str) -> str:
        """Generates a complete QSS stylesheet for the given theme.

        Args:
            theme_key: Theme identifier (light, dark, high-contrast)

        Returns:
            Complete QSS stylesheet string
        """
        palette = self.get_palette(theme_key)
        try:
            return QSS_TEMPLATE.format(**palette)
        except KeyError as e:
            logger.error("Theme palette missing key: %s", e)
            return QSS_TEMPLATE.format(**PALETTE_LIGHT)

    def register_theme(self, key: str, palette: dict):
        """Registers a custom theme.

        Args:
            key: Unique theme identifier
            palette: Dict with all required color keys (see PALETTE_LIGHT for reference)
        """
        required = set(PALETTE_LIGHT.keys())
        missing = required - set(palette.keys())
        if missing:
            raise ValueError(f"Palette missing keys: {missing}")
        self._themes[key] = palette

    def get_delegate_colors(self, theme_key: str) -> dict:
        """Returns colors needed by MediaItemDelegate for painting.

        This allows the delegate to use theme-aware colors without
        parsing QSS.
        """
        p = self.get_palette(theme_key)
        return {
            "text_primary": p["text_primary"],
            "text_secondary": p["text_secondary"],
            "text_muted": p["text_muted"],
            "accent": p["accent"],
            "favorite": p["favorite"],
            "bg_alt_row": p["bg_alt_row"],
        }
